name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Branche à partir de laquelle déployer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Récupère le code
      - uses: actions/checkout@v3

      # Déploie les fichiers directement depuis la racine
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # Racine du dépôt où se trouvent index.html, style.css, script.js